--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: 
    app: cadvisor
  name: cadvisor
  namespace: kube-system
spec: 
  selector: 
    matchLabels: 
      app: cadvisor
  template: 
    metadata: 
      labels: 
        app: cadvisor
        version: v0.31.0
    spec: 
      automountServiceAccountToken: false
      containers: 
        - 
          image: "google/cadvisor:v0.31.0"
          name: cadvisor
          ports: 
            - 
              containerPort: 8080
              hostPort: 31194
              name: http
              protocol: TCP
          resources: 
            limits: 
              cpu: 400m
            requests: 
              cpu: 250m
              memory: 250Mi
          volumeMounts: 
            - 
              mountPath: /rootfs
              name: rootfs
              readOnly: true
            - 
              mountPath: /var/run
              name: var-run
              readOnly: true
            - 
              mountPath: /sys
              name: sys
              readOnly: true
            - 
              mountPath: /var/lib/docker
              name: docker
              readOnly: true
            - 
              mountPath: /dev/disk
              name: disk
              readOnly: true
      terminationGracePeriodSeconds: 30
      tolerations: 
        - 
          effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes: 
        - 
          hostPath: 
            path: /
          name: rootfs
        - 
          hostPath: 
            path: /var/run
          name: var-run
        - 
          hostPath: 
            path: /sys
          name: sys
        - 
          hostPath: 
            path: /dev/disk
          name: disk
